### ISSUE TITLE
Issue Installing pySCTransform

### ISSUE THREAD

**Issue by ScreachingFire** [saketkc/pySCTransform#11]
* Python version: 3.8
* Operating System: MacOS Montery on an M1 Mac

### Description

I am trying to install pySCTransform and am coming across an issue that results in the installation crashing before it can finish. These are the commands I ran trying to install:
`mamba install -c conda-forge scanpy python-igraph leidenalg`
`pip install git+https://github.com/saketkc/pysctransform.git`

### What I Did

Looking at the errors I assumed it was an issue with KDEpy, so I manually reinstalled it(version 1.0.2) and tried again. Still didn't work so I tried updating pip but I got the same issue of:

> ERROR: Could not find a version that satisfies the requirement KDEpy>=1.1.0 (from versions: 0.1, 0.2, 0.3, 0.4, 0.5, 0.5.1, 0.5.2, 0.5.3, 0.5.4, 0.5.5, 0.5.6, 0.6, 0.6.9, 0.6.10, 0.6.11, 1.0.2)

> ERROR: No matching distribution found for KDEpy>=1.1.0

I don't really know where to go from here, none of the other error messages point out anything to me so I was hoping you could help. Here is the full log from when it crashes:

```
Collecting git+https://github.com/saketkc/pysctransform.git
  Cloning https://github.com/saketkc/pysctransform.git to /private/var/folders/45/cjwfv01d5k3bnm6zjrj48glc0000gn/T/pip-req-build-g0bw2hkq
  Running command git clone --filter=blob:none --quiet https://github.com/saketkc/pysctransform.git /private/var/folders/45/cjwfv01d5k3bnm6zjrj48glc0000gn/T/pip-req-build-g0bw2hkq
  Resolved https://github.com/saketkc/pysctransform.git to commit d14af48c8c1bbceb132964df202e35b7b38cc3e6
  Preparing metadata (setup.py) ... error
  error: subprocess-exited-with-error
  
  × python setup.py egg_info did not run successfully.
  │ exit code: 1
  ╰─> [35 lines of output]
      ERROR: Could not find a version that satisfies the requirement KDEpy>=1.1.0 (from versions: 0.1, 0.2, 0.3, 0.4, 0.5, 0.5.1, 0.5.2, 0.5.3, 0.5.4, 0.5.5, 0.5.6, 0.6, 0.6.9, 0.6.10, 0.6.11, 1.0.2)
      ERROR: No matching distribution found for KDEpy>=1.1.0
      /Users/name/mambaforge/envs/scRNAseqP38/lib/python3.8/site-packages/setuptools/installer.py:27: SetuptoolsDeprecationWarning: setuptools.installer is deprecated. Requirements should be satisfied by a PEP 517 installer.
        warnings.warn(
      Traceback (most recent call last):
        File "/Users/name/mambaforge/envs/scRNAseqP38/lib/python3.8/site-packages/setuptools/installer.py", line 82, in fetch_build_egg
          subprocess.check_call(cmd)
        File "/Users/name/mambaforge/envs/scRNAseqP38/lib/python3.8/subprocess.py", line 364, in check_call
          raise CalledProcessError(retcode, cmd)
      subprocess.CalledProcessError: Command '['/Users/name/mambaforge/envs/scRNAseqP38/bin/python3.8', '-m', 'pip', '--disable-pip-version-check', 'wheel', '--no-deps', '-w', '/var/folders/45/cjwfv01d5k3bnm6zjrj48glc0000gn/T/tmpxbkc0215', '--quiet', 'KDEpy>=1.1.0']' returned non-zero exit status 1.
      
      The above exception was the direct cause of the following exception:
      
      Traceback (most recent call last):
        File "<string>", line 2, in <module>
        File "<pip-setuptools-caller>", line 34, in <module>
        File "/private/var/folders/45/cjwfv01d5k3bnm6zjrj48glc0000gn/T/pip-req-build-g0bw2hkq/setup.py", line 18, in <module>
          setup(
        File "/Users/name/mambaforge/envs/scRNAseqP38/lib/python3.8/site-packages/setuptools/__init__.py", line 86, in setup
          _install_setup_requires(attrs)
        File "/Users/name/mambaforge/envs/scRNAseqP38/lib/python3.8/site-packages/setuptools/__init__.py", line 80, in _install_setup_requires
          dist.fetch_build_eggs(dist.setup_requires)
        File "/Users/name/mambaforge/envs/scRNAseqP38/lib/python3.8/site-packages/setuptools/dist.py", line 874, in fetch_build_eggs
          resolved_dists = pkg_resources.working_set.resolve(
        File "/Users/name/mambaforge/envs/scRNAseqP38/lib/python3.8/site-packages/pkg_resources/__init__.py", line 789, in resolve
          dist = best[req.key] = env.best_match(
        File "/Users/name/mambaforge/envs/scRNAseqP38/lib/python3.8/site-packages/pkg_resources/__init__.py", line 1075, in best_match
          return self.obtain(req, installer)
        File "/Users/name/mambaforge/envs/scRNAseqP38/lib/python3.8/site-packages/pkg_resources/__init__.py", line 1087, in obtain
          return installer(requirement)
        File "/Users/name/mambaforge/envs/scRNAseqP38/lib/python3.8/site-packages/setuptools/dist.py", line 944, in fetch_build_egg
          return fetch_build_egg(self, req)
        File "/Users/name/mambaforge/envs/scRNAseqP38/lib/python3.8/site-packages/setuptools/installer.py", line 84, in fetch_build_egg
          raise DistutilsError(str(e)) from e
      distutils.errors.DistutilsError: Command '['/Users/tonamedp/mambaforge/envs/scRNAseqP38/bin/python3.8', '-m', 'pip', '--disable-pip-version-check', 'wheel', '--no-deps', '-w', '/var/folders/45/cjwfv01d5k3bnm6zjrj48glc0000gn/T/tmpxbkc0215', '--quiet', 'KDEpy>=1.1.0']' returned non-zero exit status 1.
      [end of output]
  
  note: This error originates from a subprocess, and is likely not a problem with pip.
error: metadata-generation-failed

× Encountered error while generating package metadata.
╰─> See above for output.

note: This is an issue with the package mentioned above, not pip.
hint: See above for details.
```

Any help would be appreciated!

**Comment by ScreachingFire** [comment]
Okay so looking over this once again I think it's an issue with KDEpy, as it will not let me install version 1.1.0 and gives me the error "No matching distribution found for KDEpy>=1.1.0". From what I have been reading translates to they don't support the OS I'm on. And I'm seeing similar issues on the KDEpy GitHub of installation failing on M1 Macs, so I think I shall give up here until they release support for apple silicon chips.

I will be getting a new computer running Windows in the future, so hopefully everything will work fine then.
Have a nice day!
