### ISSUE TITLE
scTransform v2 returning 'no attribute index'

### ISSUE THREAD

**Issue by Tobi1kenobi** [saketkc/pySCTransform#12]
* pySCTranscform version:
pysctransform             0.1.1                    pypi_0    pypi
bioconductor-glmgampoi    1.10.0            r42hc247a5b_0    bioconda
numpy                     1.23.5           py39h3d75532_0    conda-forge
* Python version: 
python                    3.9.16               h7a1cb2a_0  
* Operating System:
Ubuntu 18.04

### Description

I have been trying to get the scTransform v2 to run on my input data and the PBMC3k dataset. scTransform v1 seems to work both on the PBMC dataset and my dataset (however has been running out of memory and crashing on my dataset so still confirming).

### What I Did

I ran the below command as per the tutorial with the intention of getting transformed counts:

```
vst_out = vst(
    adata.layers['counts'].T,
    gene_names=adata.var_names.tolist(),
    cell_names=adata.obs_names.tolist(),
    method="fix-slope",
    exclude_poisson=True,
    correct_counts=True,
    verbosity=1)
```
However it crashes and returns the following error which implies that `fit.names.index` does not exist? Is this an issue with my version of glmgampoi possibly?
```
----------------------------------------------------------------------
RemoteTraceback                           Traceback (most recent call last)
RemoteTraceback: 
"""
Traceback (most recent call last):
  File "~/conda-envs/sctpy/lib/python3.9/multiprocessing/pool.py", line 125, in worker
    result = (True, func(*args, **kwds))
  File "~/conda-envs/sctpy/lib/python3.9/site-packages/joblib/_parallel_backends.py", line 620, in __call__
    return self.func(*args, **kwargs)
  File "~/conda-envs/sctpy/lib/python3.9/site-packages/joblib/parallel.py", line 288, in __call__
    return [func(*args, **kwargs)
  File "~/conda-envs/sctpy/lib/python3.9/site-packages/joblib/parallel.py", line 288, in <listcomp>
    return [func(*args, **kwargs)
  File "~/conda-envs/sctpy/lib/python3.9/site-packages/pysctransform/pysctransform.py", line 206, in get_model_params_pergene_glmgp_offset
    params = fit_glmgp_offset(
  File "~/conda-envs/sctpy/lib/python3.9/site-packages/pysctransform/fit_glmgp.py", line 58, in fit_glmgp_offset
    overdispersions = fit[fit.names.index("overdispersions")]
AttributeError: 'numpy.ndarray' object has no attribute 'index'
"""

The above exception was the direct cause of the following exception:

AttributeError                            Traceback (most recent call last)
Input In [3], in <cell line: 1>()
----> 1 vst_out = vst(
      2     adata.layers['counts'].T,
      3     gene_names=adata.var_names.tolist(),
      4     cell_names=adata.obs_names.tolist(),
      5     method="fix-slope",
      6     exclude_poisson=True,
      7     correct_counts=True,
      8     verbosity=1)

File ~/conda-envs/sctpy/lib/python3.9/site-packages/pysctransform/pysctransform.py:629, in vst(umi, gene_names, cell_names, n_cells, latent_var, batch_var, gmean_eps, min_cells, n_genes, threads, method, theta_given, theta_regularization, residual_type, correct_counts, exclude_poisson, fix_slope, verbosity)
    627     useR = True
    628 elif method == "fix-slope":
--> 629     model_parameters = get_model_params_allgene_glmgp(
    630         umi_step1, data_step1, use_offset=True
    631     )
    632     model_parameters.index = genes_step1
    633     useR = True

File ~/conda-envs/sctpy/lib/python3.9/site-packages/pysctransform/pysctransform.py:219, in get_model_params_allgene_glmgp(umi, coldata, bin_size, threads, use_offset, verbosity)
    217 log_umi = npy.log(npy.ravel(umi.sum(0)))
    218 if use_offset:
--> 219     results = Parallel(n_jobs=threads, backend="multiprocessing", batch_size=500)(
    220         delayed(get_model_params_pergene_glmgp_offset)(row, coldata, log_umi)
    221         for row in umi
    222     )
    223 else:
    224     results = Parallel(n_jobs=threads, backend="multiprocessing", batch_size=500)(
    225         delayed(get_model_params_pergene_glmgp)(row, coldata) for row in umi
    226     )

File ~/conda-envs/sctpy/lib/python3.9/site-packages/joblib/parallel.py:1098, in Parallel.__call__(self, iterable)
   1095     self._iterating = False
   1097 with self._backend.retrieval_context():
-> 1098     self.retrieve()
   1099 # Make sure that we get a last message telling us we are done
   1100 elapsed_time = time.time() - self._start_time

File ~/conda-envs/sctpy/lib/python3.9/site-packages/joblib/parallel.py:975, in Parallel.retrieve(self)
    973 try:
    974     if getattr(self._backend, 'supports_timeout', False):
--> 975         self._output.extend(job.get(timeout=self.timeout))
    976     else:
    977         self._output.extend(job.get())

File ~/conda-envs/sctpy/lib/python3.9/multiprocessing/pool.py:771, in ApplyResult.get(self, timeout)
    769     return self._value
    770 else:
--> 771     raise self._value

AttributeError: 'numpy.ndarray' object has no attribute 'index'
```

**Comment by Tobi1kenobi** [comment]
This is most likely a result of an rpy2 deprecation of the extraction method `overdispersions = fit[fit.names.index("overdispersions")]`. If I replace this with `overdispersions = fit.rx2("overdispersions")` as well as replace all other occurrences of the names.index extraction approach, the code works fine.

I have tried installing an earlier version of rpy2 but conda gives conflict issues so this seems to be a suitable fix.

**Comment by saketkc** [comment]
Apologies for not noticing this earlier. Thanks for suggesting the fix. I will update it in the next version.
