### ISSUE TITLE
[BUG] basic workflow currently failing: dependency underspecification? 

### ISSUE THREAD

**Issue by alexlenail** [saketkc/pySCTransform#9]
* pySCTranscform version: '0.1.1'
* Commit SHA: this morning
* Python version: 3.10.5
* Operating System: centos 7

### Description

This morning I did: 
```
conda create -n pysct louvain leidenalg scanpy rpy2 bioconductor-glmgampoi pip
/home/gridsan/lenail/.conda/envs/pysct/bin/pip install git+https://github.com/saketkc/pysctransform.git
conda activate pysct
```

And then I tried: 

```
adata.obsm["pearson_residuals"] = SCTransform(adata, var_features_n=3000, vst_flavor='v2')
```

But I got: 

```
  File "/home/gridsan/lenail/.conda/envs/pysct/lib/python3.10/site-packages/pandas/core/groupby/groupby.py", line 1423, in apply
    result = self._python_apply_general(f, self._selected_obj)
  File "/home/gridsan/lenail/.conda/envs/pysct/lib/python3.10/site-packages/pandas/core/groupby/groupby.py", line 1464, in _python_apply_general
    values, mutated = self.grouper.apply(f, data, self.axis)
  File "/home/gridsan/lenail/.conda/envs/pysct/lib/python3.10/site-packages/pandas/core/groupby/ops.py", line 761, in apply
    res = f(group)
  File "/home/gridsan/lenail/.conda/envs/pysct/lib/python3.10/site-packages/pysctransform/pysctransform.py", line 75, in robust_scale
    return (x - npy.median(x)) / (
  File "<__array_function__ internals>", line 180, in median
  File "/home/gridsan/lenail/.conda/envs/pysct/lib/python3.10/site-packages/numpy/lib/function_base.py", line 3793, in median
    r, k = _ureduce(a, func=_median, axis=axis, out=out,
  File "/home/gridsan/lenail/.conda/envs/pysct/lib/python3.10/site-packages/numpy/lib/function_base.py", line 3702, in _ureduce
    r = func(a, **kwargs)
  File "/home/gridsan/lenail/.conda/envs/pysct/lib/python3.10/site-packages/numpy/lib/function_base.py", line 3828, in _median
    part = partition(a, kth, axis=axis)
  File "<__array_function__ internals>", line 180, in partition
  File "/home/gridsan/lenail/.conda/envs/pysct/lib/python3.10/site-packages/numpy/core/fromnumeric.py", line 758, in partition
    a.partition(kth, axis=axis, kind=kind, order=order)
TypeError: '<' not supported between instances of 'pandas._libs.interval.Interval' and 'float'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/gridsan/lenail/PFC_aging/3_Normalize.py", line 9, in <module>
    adata.obsm["pearson_residuals"] = SCTransform(adata, var_features_n=3000, vst_flavor='v2')
  File "/home/gridsan/lenail/.conda/envs/pysct/lib/python3.10/site-packages/pysctransform/pysctransform.py", line 859, in SCTransform
    vst_out = vst(
  File "/home/gridsan/lenail/.conda/envs/pysct/lib/python3.10/site-packages/pysctransform/pysctransform.py", line 686, in vst
    col_outliers = is_outlier(
  File "/home/gridsan/lenail/.conda/envs/pysct/lib/python3.10/site-packages/pysctransform/pysctransform.py", line 105, in is_outlier
    score1 = robust_scale_binned(y, x, breaks1)
  File "/home/gridsan/lenail/.conda/envs/pysct/lib/python3.10/site-packages/pysctransform/pysctransform.py", line 86, in robust_scale_binned
    tmp = df.groupby(["bins"]).apply(robust_scale)
  File "/home/gridsan/lenail/.conda/envs/pysct/lib/python3.10/site-packages/pandas/core/groupby/groupby.py", line 1434, in apply
    return self._python_apply_general(f, self._selected_obj)
  File "/home/gridsan/lenail/.conda/envs/pysct/lib/python3.10/site-packages/pandas/core/groupby/groupby.py", line 1464, in _python_apply_general
    values, mutated = self.grouper.apply(f, data, self.axis)
  File "/home/gridsan/lenail/.conda/envs/pysct/lib/python3.10/site-packages/pandas/core/groupby/ops.py", line 761, in apply
    res = f(group)
  File "/home/gridsan/lenail/.conda/envs/pysct/lib/python3.10/site-packages/pysctransform/pysctransform.py", line 76, in robust_scale
    stats.median_absolute_deviation(x) + npy.finfo(float).eps
AttributeError: module 'scipy.stats' has no attribute 'median_absolute_deviation'. Did you mean: 'median_abs_deviation'?
(pysct) lenail@d-5-12-4:~/$
```

Which look to me mostly like numpy/pandas version issues.

**Comment by alexlenail** [comment]
Also, would it be possible to bump the scanpy version dependency?

**Comment by saketkc** [comment]
Thanks for the bug report. This should now be fixed in master with https://github.com/saketkc/pySCTransform/commit/683fe3837b0c0cdc682bbe3da7c3ac01f391e706
